apiVersion: apps/v1  
kind: Deployment  
metadata:  
  labels:  
    app: echo-server   
  name: echo-server  
  namespace: echo-server 
spec:  
  selector:  
    matchLabels:  
      app: echo-server  
  replicas: 1  
  template:  
    metadata:  
      labels:  
        app: echo-server    
      name: echo-server  
    spec:  
      containers:  
        - name: echo-server  
          image: 528977880076.dkr.ecr.eu-central-1.amazonaws.com/echo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:  
            limits:  
              cpu: 500m  
              memory: 250Mi  
            requests:  
              cpu: 100m  
              memory: 10Mi  
          volumeMounts:  
            - readOnly: true  
              mountPath: app/templates  
              name: html-files  
      volumes:  
        - name: html-files  
          configMap:  
            name: echo-server-static-files  